GET http://localhost:8080/download/tasaf.213213123.asdf HTTP/1.1
content-type: application/json
Accept-Encoding: gzip

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
GET http://localhost:8080/health HTTP/1.1
content-type: application/json

###
POST http://localhost:8080/api/mp3convert HTTP/1.1
content-type: application/json

{
    "url": "https://rr2---sn-5cjvh-up5s.googlevideo.com/videoplayback?expire=1682234791&ei=R4lEZIqfHtWax_APu52pwAI&ip=31.171.154.137&id=o-APKGCdFAOaeYvOa34eggOD02MubSnZIuPua51MFDjaL2&itag=18&source=youtube&requiressl=yes&mh=Uk&mm=31%2C29&mn=sn-5cjvh-up5s%2Csn-nv47znel&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=26&initcwndbps=1671250&spc=99c5CeLkkgmU59ul4LXfMy2KCr5aMzppuDsHqeKiug&vprv=1&mime=video%2Fmp4&ns=RCCyMz-KODBmeVFr0EDzg-wM&cnr=14&ratebypass=yes&dur=3642.537&lmt=1641599170729126&mt=1682212855&fvip=1&fexp=24007246&c=WEB&txp=5319224&n=k4ZLEyfVF4AC7Q&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgCsbAByUyqpJFgn2XL4N4xCvF8Sq1uHcjh0PMHfndXMUCIQCwhFECSzAJ_PidaVn93xGi1fqc9cGMi1WgcyVvzWldOw%3D%3D&sig=AOq0QJ8wRAIge-DO594-dQ9ZwX-UDGvQZq0fMTz1XHhovvZvSRGgybMCIF9Jtjo8gtOKsKzWRNLe4P7Q3kuUbxoSA5WB7w_3qFx-"
}


###
// REUQEST STATIC
GET http://localhost:8080/api/download/1682248062572835400.1212.sad HTTP/1.1
content-type: application/json
